### ISSUE TITLE
Silence output in serial mode

### ISSUE THREAD

**Issue by keith** [atlassian/bazel-tools#130]
In some of our use cases we run some things in parallel, and then some serially later. To do this we have 2 different multirun targets we run back to back. In the parallel case when it's successful there is no output, which makes the output from the serial case a bit surprising. Would it be reasonable to have a option on `multirun` that silences the `running [target]` output when running serially?

**Comment by ash2k** [comment]
Yes, PRs welcome! :)

**Comment by keith** [comment]
https://github.com/atlassian/bazel-tools/pull/131
