### ISSUE TITLE
GoMetalinter using bazel

### ISSUE THREAD

**Issue by kkumar1234** [atlassian/bazel-tools#19]
Hi,

I am trying to use gometalinter using bazel build system with reference the example code shared in this repo. Layout of codebase
<root>
     WORKSPACE
      BUILD
      <dir1> --> uses third party golang github packages

WORKSPACE
load("@com_github_atlassian_bazel_tools//gometalinter:deps.bzl", "gometalinter_dependencies")
gometalinter_dependencies()

BUILD
load("@com_github_atlassian_bazel_tools//gometalinter:def.bzl", "gometalinter")
gometalinter(
        name = "gometalinter",
        config = "//:gometalinter.json",
        paths = [
                "<dir1>/...",
                ],
        prefix = "<repo_path>",
)

On executing "bazel run //:gometalinter", bazel is having issues importing third party github repos internally used by code in dir1 folder.

Can you please let me know any solution for this?
The same is easily achievable using deps for go_binary/cc_binary, etc

Thanks
Kailash

**Comment by ash2k** [comment]
Hey, can you share the exact full `WORKSPACE` and `BUILD` files and also the exact full error message that bazel is giving you? I cannot help with just the information you have provided, sorry.

**Comment by amckague** [comment]
Double checking: which version of bazel are you running?

**Comment by kkumar1234** [comment]
Hi,

I am using 0.16.0 version of bazel. Please find below output of version command.

bazel version

Build label: 0.16.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jul 31 17:01:24 2018 (1533056484)

Thanks
Kailash

**Comment by amckague** [comment]
Can you paste the contents of those files rather than an image? (so I can attempt to reproduce the issue)

**Comment by kkumar1234** [comment]
[BUILD.txt](https://github.com/atlassian/bazel-tools/files/2334776/BUILD.txt)
[WORKSPACE.txt](https://github.com/atlassian/bazel-tools/files/2334777/WORKSPACE.txt)
Hi,

I have uploaded the file in text format. Steps to reproduce:

go get -u github.com/stretchr/testify
cd $GOPATH/src/github.com/stretchr/testify
copy BUILD and WORKSPACE to root of testify repo.
execute gometalinter rule using bazel

Thanks
Kailash

**Comment by amckague** [comment]
Is there a typo in the attached files?

```
bazel run //:gometalinter
ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': Error downloading [https://github.com/bazelbuild/rules_go/releases/download/0.15.1/rules_go-0.15.1.tar.gz] to /home/amckague/.cache/bazel/_bazel_amckague/d1309ac1e2719cdf777c0d6e936fc92b/external/io_bazel_rules_go/rules_go-0.15.1.tar.gz: Checksum was 5f3b0304cdf0c505ec9e5b3c4fc4a87b5ca21b13d8ecc780c97df3d1809b9ce6 but wanted 5756a4ad75b3703eb68249d50e23f5d64eaf1593e886b9aa931aa6e938c4e301
ERROR: error loading package '': Encountered error while reading extension file 'go/def.bzl': no such package '@io_bazel_rules_go//go': Error downloading [https://github.com/bazelbuild/rules_go/releases/download/0.15.1/rules_go-0.15.1.tar.gz] to /home/amckague/.cache/bazel/_bazel_amckague/d1309ac1e2719cdf777c0d6e936fc92b/external/io_bazel_rules_go/rules_go-0.15.1.tar.gz: Checksum was 5f3b0304cdf0c505ec9e5b3c4fc4a87b5ca21b13d8ecc780c97df3d1809b9ce6 but wanted 5756a4ad75b3703eb68249d50e23f5d64eaf1593e886b9aa931aa6e938c4e301
INFO: Elapsed time: 5.107s
INFO: 0 processes.
```
 Removing references to the this lib and it's rules doesn't help the above error.

**Comment by ash2k** [comment]
Another issue that I noticed is that `go_rules_dependencies()` and `go_register_toolchains()` are invoked twice. The second pair of calls can be removed.

**Comment by kkumar1234** [comment]
Hi,

The same WORKSPACE file is working fine for me. 
In your case, line 4 in WORKSPACE file having sha256 can be replaced by 5f3b0304cdf0c505ec9e5b3c4fc4a87b5ca21b13d8ecc780c97df3d1809b9ce6.

This will ensure checksum validation completes.
I agree second pair is redundant and can be removed.

Also, please try bazel run command keeping vendor directory and then without any vendor directory in the git repo.

Thanks
Kailash

**Comment by amckague** [comment]
Does `bazel clean --expunge` change the error for you?

The attached WORKSPACE file below works for me. metalinter runs and reports various linting issues (including linting issues in /vendor). I suggest adding config = "//:.gometalinter.json", to the gometalinter configuration in BUILD.bazel and use it to configure linting to ignore the vendor folder altogether.

[WORKSPACE.txt](https://github.com/atlassian/bazel-tools/files/2336408/WORKSPACE.txt)

**Comment by ash2k** [comment]
Also see https://github.com/atlassian/smith/blob/master/.gometalinter.json and https://github.com/atlassian/smith/blob/master/BUILD.bazel#L68-L79 for inspiration =)
