### ISSUE TITLE
gometalinter (varcheck) cannot import imports

### ISSUE THREAD

**Issue by prestonvanloon** [atlassian/bazel-tools#24]
Is there any way to provide the external dependencies or generated code to varcheck?

**Comment by ash2k** [comment]
I haven't looked into doing this but off the top of my head I think there is no way. gometalinter and the linters are not aware of bazel and I don't immediately see a way to provide any external dependencies or generated code as additional sources to check/use for linters. This rule is written with only vendor directory as the libraries source in mind.
Any suggestions welcome.
Somewhat related: https://github.com/bazelbuild/rules_go/issues/1292 https://github.com/bazelbuild/rules_go/issues/626 https://github.com/bazelbuild/rules_go/issues/511

**Comment by prestonvanloon** [comment]
Thanks!

I'm using external go_repositories and trying to make this work. I've subscribed to those issues and hopefully, I can come back here with a resolution.

**Comment by ash2k** [comment]
The way forward is to use `nogo`. I've documented the limitations linting rules in this repository have, so I'm closing this issue.
