### ISSUE TITLE
golangci-lint does not depend on SDK libs

### ISSUE THREAD

**Issue by terinjokes** [atlassian/bazel-tools#51]
The golangci-lint rule does not depend on the SDK libraries. This results in a warning from govet (and possibly other linters):

```console
WARN [runner] Can't run linter govet: can't typecheck package: can't init std types: import of type fmt.Stringer failed: can't find import: fmt
```

By adding `depset(sdk.libs)` to the transitive dependencies list the compiled libraries are added to execution directory and everything is happy.

https://github.com/atlassian/bazel-tools/blob/02472d814d1867de2ad75801760732c9e595c9d9/golangcilint/def.bzl#L27-L30

**Comment by ash2k** [comment]
@terinjokes if you send a PR I'll happily merge it. Also, sign the CLA please if you do so.

**Comment by terinjokes** [comment]
Hey Mikhail.

It doesn't look like I can view the CLA without providing personal
information to DocuSign. So I don't think I'll be doing so.

Hopefully my bug reports provide enough information to replicate and
resolve.
