### ISSUE TITLE
golangci-lint rule should cache output results

### ISSUE THREAD

**Issue by dxj910804** [atlassian/bazel-tools#60]
golangci-lint rule runs the linter via a bash command. However, the issue is that even if the source files are not changed, the linter is invoked.

It is really two steps：
[run linter] + [cache linter-found issues]

If source code is not changed, then just output [cache linter-found issues] skipping [run linter] step.

**Comment by ash2k** [comment]
[nogo](https://github.com/bazelbuild/rules_go/blob/master/go/nogo.rst) is a much better solution than golangci-lint. It has caching/it is incremental, etc. The golangci-lint cannot really be fixed - the fix would be to turn it into nogo =) The right path forward is to migrate more linters to nogo framework.

**Comment by dxj910804** [comment]
thanks for the response and we are trying on nogo.
