### ISSUE TITLE
Run golangci-lint in a subfolder

### ISSUE THREAD

**Issue by radhus** [atlassian/bazel-tools#65]
I have a repo with the structure:
```
/WORKSPACE
/src/go.mod
/src/a/main.go
/src/a/.golangci.yml
/src/b/main.go
/src/b/.golangci.yml
```

As `/src/a` and `/src/b` has separate linter configurations, it would be nice to run golangci-lint inside `/src/a` and `/src/b` separate.

As the current rule symlink the workspace root `/`, it would be nice if you could specify it to change directory into `src/a` before running golangci-lint.

**Comment by ash2k** [comment]
Thanks for the suggestion. It seems what you need is possible today. You can have two golangci-lint targets, once for each directory. Each of those targets can have its `config` attribute specifying the relevant configuration file and its `paths` attribute specifying which directories to lint. The drawback of this approach is duplication of some work - parsing sdk and shared library sources (if any). But this is inevitable if you want to have per-directory configuration, unless the linter natively supports that (I haven't checked).

To step back a bit. Are you using this linter rule with modules and vendoring? I think long term it's better to migrate to nogo from rules_go. It has quite a few benefits. Most important is that it is incremental.

**Comment by radhus** [comment]
Sorry for the late reply. Thanks @ash2k , the problem with my repo was that the `go.mod` was under `/src` and not `/`, which made it fail due to symlinks. We'll also look into nogo for the future :)
