### ISSUE TITLE
Pick up default config file for golangci.yml

### ISSUE THREAD

**Issue by radhus** [atlassian/bazel-tools#66]
If a `config` attribute isn't passed in to the `golangcilint`, the flag `--no-config` is appended to `golangci-lint run`.

Is there any need for this?

If it would be dropped, an existing `.golangci.yml` file would be picked up if present instead. That would make it easy to write generic Bazel rules without having to specify the config.

**Comment by ash2k** [comment]
It's part of bazel approach to have all inputs specific explicitly. It's actually impossible because this linter is not very bazel friendly but by having the config specified explicitly we get one step closer to this ideal state. This is just how things in bazel work.
