### ISSUE TITLE
[multirun] ctrl-c will leave the started processes running

### ISSUE THREAD

**Issue by funkyKay** [atlassian/bazel-tools#67]
my current workaround is to add this at the end of my runcommand
```bash
<some starting command>; kill $(ps | grep '[n]ame-of-the-multirun-target' | awk '{print $1}')
```

**Comment by ash2k** [comment]
Thanks for reporting this. There is likely a bug in the shell wrapper script. I'll have a look later.

**Comment by ash2k** [comment]
@funkyKay hey, sorry for the delay in fixing this. Are you able to test the updated rule from #72? That'd be awesome if you could confirm it fixes the issue for you.

**Comment by funkyKay** [comment]
@ash2k yes its working. thank you.
