### ISSUE TITLE
[multirun] shorter labels

### ISSUE THREAD

**Issue by Toxicable** [atlassian/bazel-tools#70]
The bazel labels take up a lot of room in the console, for our use case console output is pretty important.
Could we add some config that would allow for specifying some shorter name for the label.
For example with the label `//apps/my-app:bin` we'd like to use `MA` instead

**Comment by ash2k** [comment]
Sounds reasonable. Perhaps a [label_keyed_string_dict](https://docs.bazel.build/versions/master/skylark/lib/attr.html#label_keyed_string_dict) attribute to specify remapping.

**Comment by Toxicable** [comment]
sounds good to me, could perhaphs do it as a seprate attribute `labeled_commands`? to avoid breaking changes to the `command` attribute

**Comment by ash2k** [comment]
👍
