### ISSUE TITLE
Support data attribute in multirun command

### ISSUE THREAD

**Issue by rockwotj** [atlassian/bazel-tools#78]
I'd like to have a config in the command rule, how hard would it be to add a data dep like specified here: https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes

**Comment by ash2k** [comment]
I think the `data` attribute, just like the most of the other attributes listed on that page, is there on the rule out of the box. Have you tried specifying it?

**Comment by rockwotj** [comment]
I have tried specifying it and I get this error: ` no such attribute 'data' in '_command' rule`

It seems other rules have this specified explicitly, see:
https://github.com/bazelbuild/rules_go/blob/master/go/private/rules/binary.bzl#L57
https://github.com/bazelbuild/rules_kotlin/blob/master/kotlin/internal/jvm/jvm.bzl#L179
https://github.com/bazelbuild/rules_kotlin/blob/master/kotlin/internal/jvm/impl.bzl#L36-L37
