### ISSUE TITLE
Support make variable substitution in command.args

### ISSUE THREAD

**Issue by rockwotj** [atlassian/bazel-tools#79]
I think it'd be nice to allow for multirun to support environment variables, right now I have a wrapper script to resolve them

**Comment by ash2k** [comment]
What use case do you have in mind? It does support setting environment variables for commands via the `command` rule (see the readme).

**Comment by rockwotj** [comment]
No not via that, it's actually for things like `$RUNFILES_DIR` or `$BUILD_WORKSPACE_DIRECTORY`

**Comment by ash2k** [comment]
Ok, can you give me an example of what you have in mind? I.e. an example of what you would like this rule to be able to do.

**Comment by rockwotj** [comment]
Sorry I think I actually mean make variable substitution: https://docs.bazel.build/versions/master/be/make-variables.html#predefined_label_variables

Other [binary commands do this with args][1] and is useful when pared with https://github.com/atlassian/bazel-tools/issues/78

[1]: https://docs.bazel.build/versions/master/be/common-definitions.html#binary.args

**Comment by ash2k** [comment]
Make variable expansion method [is deprecated](https://docs.bazel.build/versions/master/skylark/lib/ctx.html#expand_make_variables) (was done here https://github.com/bazelbuild/bazel/commit/6ab8ea1cb7403bbedde2d6f83db74b1a96bd1c7e without explanation) and there is [no replacement](https://github.com/bazelbuild/bazel/issues/5859) at the moment. However, `$(location label)` syntax can be enabled via [`ctx.expand_location()`](https://docs.bazel.build/versions/master/skylark/lib/ctx.html#expand_location) which is not deprecated. Do you think that would be enough?

**Comment by rockwotj** [comment]
Yes, I don't use anything other than location expanding anyways.
