### ISSUE TITLE
use of multirun with ibazel

### ISSUE THREAD

**Issue by joprice** [atlassian/bazel-tools#87]
I am trying to use ibazel with multirun, but having an issue with tag propagation: One of the two commands has the tags "ibazel_notify_changes" and "ibazel_live_reload" configured, in order to respond to ibazel reload commands. If I don't add these tags to the multirun call, then no reloading happens. If I do add them, the process that doesn't support ibazel reloading gets built, but never gets restarted.

**Comment by ash2k** [comment]
I'm not familiar with ibazel so I cannot advise on the correct use of it. If you can suggest what needs to be fixed in multirun and why, I can look into it.

**Comment by joprice** [comment]
I'm not totally sure myself how it it's meant to work. I'm still looking into that and will try to suggest something when I know more.
